#!/bin/bash
export PATH=./scripts:$PATH
export RUBYLIB=./lib
./test/test1_help
./test/test2_env
./test/test3_no_env
./test/test4_current_idiom
./test/test5_no_root
./test/test6_root_first
./test/test7_flexible
